id: AED98A43F
title: 'Fully Blossomed Learning and Contemplation: A Praise of the Great Spiritual
  Friend Jamyang Gyaltsen'
type: translation
pechas:
- I718E7E45
- I32D96A28
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:02:41.485144
  last_modified_at: 2023-01-04 12:02:41.485646
  collections:
  - Jamyang Gyaltsen Series
  - Works of Tibetan Masters
alignment_to_base:
  I718E7E45/A372: 5D55
  I32D96A28/C177: 5D55
